### ISSUE TITLE
Check browser compatibility on main browsers - Chrome, Mozilla and Safari

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#289]
Look at all pages and look for missing styling such as;
- Missing padding between elements
- Missing fonts
- Padding between elements where there shouldn't be

- [x] Desktop Safari
- [x] Desktop Chrome
- [x] Desktop Firefox
- [x] iPhone Safari
- [x] iPad Safari
- [x] Android Chrome
- [x] Android Samsung Internet Browser
- [x] Android Firefox

---

**Findings**

- [x] Safari: (both ios and desktop) Arrows are visible in FAQ accordion
- [x] Phones: (both ios and android) Map in **new chain signup** page is too small
- [x] iPad: photo: Martijn van den Dobbelsteen/de Brug on Home Page displays left aligned with no padding
- [x] iPad: Video box is very small on About and Home page
- [ ] iPad: find chain and new chain sign do not load and print similar error message: "A problem repeatedly occured on "url" 
      **Moved to** #347 
- [x] Android: the homepage the testimonials touch sensitivity is a tad high, it is very easy to overshoot the middle the testimonial.

**Comment by jnorlando** [comment]
- **Desktop Safari**
        Has errors in FAQ formatting
        <span>Are there rules on how much you can take out, .... Arrow Being compressed 
        <>What is an ideal group size? Text alignment is off appears centered or indented
        <>What is an ideal group size? Text alignment is off appears centered or indented
        <>How can I start using the app? Text alignment is off appears centered or indented
        <>What is an ideal group size? Text alignment is off appears centered or indented

- **iPhone Safari**
     FAQ has the same styling errors present in the browser version
     Map Box image on newchainsign up is very small
  

- **iPad Safari** 
      photo: Martijn van den Dobbelsteen/de Brug on Home Page displays left aligned with no padding
      Video box is very small on About and Home page
      find chain and new chain sign do not load and print similar error message:  "A problem repeatedly occured on "url"
      
                
    Note: all versions of safari display an arrow > next to accordion boxes on the faq leading to screen clutter with the "feather-minus" : "feather-plus" elements

**Comment by jnorlando** [comment]
**- Android Chrome** looks fine, the testimonials on the homepage's touch sensitivity is a little high, easy to overshoot the middle testimonial, unless you gently nudge it.

**Comment by jnorlando** [comment]
**- Android Firefox**
All pages are fine, except the /loops/new, the mapbox-gl canvas is so small it is unusable, on click it appears to freeze

**- Android Chrome**
Has the same mapbox-gl issue as firefox.
Also, on the homepage the testimonials touch sensitivity is a tad high, it is very easy to overshoot the middle the testimonial.
