### ISSUE TITLE
Optimize route order (go-tsp)

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#343]
**Add coordinates to users**
- [x] Add the coordinates to the database users table
- [x] Integrate these coordinates into existing api calls
- [x] Set coordinates from the frontend on setting address 
- [ ] #533

**Add Go TSP**
- [x] Understand [dyxj/go-tsp](https://github.com/dyxj/go-tsp)
- [x] Implement go-tsp with the following options (depending on package implementation restraints)
- [x] Add an `optimize route` button to run the `go-tsp` route

:warning: When a new user is added or an old removed: `go-tsp` does not find a new route!

**Comment by lil5** [comment]
I'll let you finish this off if you like, the go-tsp package is ready with enough features for clothingloop

**Comment by gclamigueiro** [comment]
It seems that changing latitude and longitude on Create and Edit a user is already done.  So, options 1, 2 , 3 from Add coordinates to users are completed

Example of edited users
![Example of edited users](https://github.com/the-clothing-loop/website/assets/29601619/1e75c731-41cd-4ca7-ba5e-2d2755e8e128)

Example of a new user
![Example of created user](https://github.com/the-clothing-loop/website/assets/29601619/fd3dd3fe-9c01-4b6f-9965-f87c894d4c79)

**Comment by lil5** [comment]
@gclamigueiro Thanks for mentioning, I've updated accordingly 👍
