### ISSUE TITLE
Debug logining in authentification emails

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#347]
User authentication emails are still pretty high, a user shouldn't need to verify multiple times a week from one device.

I found a lot of duplicate sent emails, people were clicking the submit button multiple times, thus sending many emails

**Comment by lil5** [comment]
iPads and iPhones can't open the Loop page without logging-out

**Comment by lil5** [comment]
@paloeka These are the three states the login page can be

![Image](https://user-images.githubusercontent.com/17646836/216047642-01c1822e-08b2-4f20-8a87-dc316df78f8b.png)
![Image](https://user-images.githubusercontent.com/17646836/216047643-661dd2c2-e9b5-4343-8750-f2c603f5db3c.png)
![Image](https://user-images.githubusercontent.com/17646836/216047644-83135b6b-d40b-4536-bb79-380866328dd4.png)

**Comment by paloeka** [comment]
What is the difference between picture 2 and 3? Is picture 2, that the email is on their way?
