### ISSUE TITLE
Add new FAQ text to website

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#350]

**Comment by lil5** [comment]
@paloeka could you send me a link to the new FAQ text I can't find it.

**Comment by paloeka** [comment]
https://docs.google.com/document/d/1rR5qKWn7fqpJasKLPrtNz5IsEIH98I2x7Bfhq3CtTtA/edit#

**Comment by lil5** [comment]
@paloeka `(only for insta highlights:) Why are the FAQ only in English?` This text doesn't make sense, the FAQ is translated in and NL, FR

**Comment by lil5** [comment]
@paloeka I've added some comments to the document

**Comment by paloeka** [comment]
One link is added, the other doc still needs to be translated, so you can leave that for now, will work on it! But I am thinking as the site is now more and more clear, do we still need a login guide? Thoughts?

**Comment by lil5** [comment]
> Sorry I should have made two files

No need to make it extra difficult but a comment in the document will more that suffice 👍

**Comment by lil5** [comment]
@paloeka Sorry one last link to add and I can finish this task.

**Comment by paloeka** [comment]
That was to Glide yes? I just pasted it in!

**Comment by lil5** [comment]
@paloeka https://docs.google.com/document/d/1rR5qKWn7fqpJasKLPrtNz5IsEIH98I2x7Bfhq3CtTtA/edit?disco=AAAAo6aN-BY
