### ISSUE TITLE
Poke host

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#351]
Users that are waiting for host approval can poke a host, this will send another email to the host.

- Max 1 poke per week ~per loop~! per user
- Add a column in database `users.last_poke`
- Add email template to remind the hosts

**Comment by lil5** [comment]
@paloeka we'll need a poke English email template.

**Comment by paloeka** [comment]
Hi,


<Name Participant> would like to join your <Loop Name> Loop. We would like you to ask to please contact them. You can find their info in Account on our website. 


Nichon, on behalf of the Clothing Loop team

**Comment by lil5** [comment]
@paloeka An email title would finish it off nicely

**Comment by paloeka** [comment]
Title: Your request to join a <loop name> has been denied

**Comment by paloeka** [comment]
Your request to join a <loop name> has been denied

**Comment by paloeka** [comment]
Title: Your request to join <Loop Name > has been denied
