### ISSUE TITLE
Allow users to login instead of trying to join a loop by re-registering

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#431]
![Screenshot 2023-03-20 at 15-46-03 The Clothing Loop Signup user](https://user-images.githubusercontent.com/17646836/226376721-d2e8822b-ae12-46ce-a9e7-09e868435398.png)

Currently trying to register using an existing user will fail and show the user an error message telling them to login.

Either;
1. Add a sign-in form next to the registration form :point_left: 
2. A failed re-registration should silently fail and try sending a login validation email instead, (this does mean people will need to fill in all their details __again__, just to find that they already have an account)

**Comment by lil5** [comment]
@paloeka what are your thoughts on this issue? I found a lot of error logs that show people are trying but to bumping into this issue.

**Comment by paloeka** [comment]
Yes, this is a common issue. 

[1] How do you envision it? An extra button between back and join?

[2] The problem arrises when people need to fill in their details again that they will write things down differently. So if that happens what to do? Register the first try and delete te second or overwrite the first, existing, contact details.

Maybe what we could do is that people need to log in, but instead afterwards get redirected to the Loop they wanted to join. I think that can be more difficult.

The problem I think what people irritate right now is that they have to fill in all their info first and than you get the pop-up message: 
![image](https://user-images.githubusercontent.com/108399021/226629256-80dee738-952b-4068-a543-3e30a8f4c9f9.png)

I think the solution maybe is that people first enter their email adresses and then go to the next page where they fill in the rest of their information (if they do not have an account). And if they have an account they get the existing pop up message. 

Additionally, (and a bit of another note) we can change the text of this error message to a more friendly version:

With a title: User already exists
You already have an account. If you want to register for this Loop, please log in first.

The lay-out is okay and the place of the pop-up screen as well. Only I would not do a "Close" but an X at the upper right corner and do "Login" in the middle with the same yellow as the "Join" button
