### ISSUE TITLE
Feature list for our Glide-app

### ISSUE THREAD

**Issue by paloeka** [the-clothing-loop/website#458]
**Production requirements**

- [x] Add images option (bulky items and bags)
- [x] Route number shown in tap of selecting a bag
- [-] Notifications (eg with bulky items when someone responded or a new bulky item is posted) #500
- [-] Push notification if the bag is longer than a week on the same address #500
- [x] In bags tab: Alert icon if the bag is longer than a week on the same address
- [x] Participants pause themselves (with slider?)
- [x] Host can edit rules text on first tab
- [x] When a participant puts the bag on her name, the date should automatically be set to today
- [x] Privacy option: participants can hide address from everyone except 2 people before and 2 people after you. (slider?)

**Nice to have**
- [-] Route optimisation for host (Gotsp) -> #343

**Comment by lil5** [comment]
> When a participant puts the bag on her name, the date should automatically be set to today

With the new app there is no date, so I'm a bit confused?

**Comment by lil5** [comment]
> Host can edit rules text on first tab

@paloeka Allowing a host to change all rules is a bit difficult with the faq being translated, maybe certain rule values can be changed, like the `Make 3 days to shop` could be a number that the host can choose, or select rules that don't apply to them.

**Comment by paloeka** [comment]
That sounds good!

**Comment by lil5** [comment]
I'm move the rest of the tasks into separate issues
