### ISSUE TITLE
Automatic close after 60 days pending participants

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#463]
Looking if we could make an automatic Closed if they have pending participants for more than 60 days. Hosts will also need to receive an email that their Loop will be closed, with a warning that if their loop will be deleted if there are pending participants for more than 90 days.

- [x] 1. Create alert email for hosts, ( of loop with 60+ days pending participants) notifying them that their loop will be set to closed if they don't accept (or deny) pending participants.
- [x] #521

**Comment by lil5** [comment]
https://github.com/eapache/queue

Use v2 queue to add a weekly cron job

**Comment by lil5** [comment]
@paloeka please send me the email text contents for step 1

**Comment by paloeka** [comment]
Dear <Host Name>,

You have a new participant waiting in your account at the Clothing Loop for over 60 days. These participants are waiting to be accepted and receive further information on how to join your Loop.
If you are too busy or the Loop is full, please Deny the participant’s request, Close your Loop for new participants & put in the Loop’s bio your reason (and if the Loop will open in the future). 

Nichon, on behalf of the Clothing Loop team

**Comment by paloeka** [comment]
Dear > Host Name >

You have a new participant waiting in your account at the Clothing Loop for over 60 days. These participants are waiting to be accepted and receive further information on how to join your Loop.
If you are too busy or the Loop is full, please Deny the participant’s request, Close your Loop for new participants & put in the Loop’s bio your reason (and if the Loop will open in the future).

Nichon, on behalf of the Clothing Loop team

- "your account" as a hyperlink to the log in page

**Comment by lil5** [comment]
@paloeka Concerning task **2.** Instead of deleting the loop I'm setting the loop to draft, say someone is on holiday, they can still reopen the loop later.

If you rather have it deleted this can still be changed

**Comment by paloeka** [comment]
I think setting it to draft is a good idea. It will take a bit more manual work from me (Paloeka). But this is better, so the Loop could continue to exist
