### ISSUE TITLE
By default set the event create price to euro, and allow zero

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#485]
During event creation, set the price currently by default to EUR
Allow setting the price value to zero

If the price is set to zero on a non free currency, revert to setting the currency to `free` when sending to server

**Comment by NatalieWilson19** [comment]
Hey Lucian, I'd like to work on this

**Comment by lil5** [comment]
I believe someone else has been working on it, I can't remember atm, I'll make a note to ask in the dev meeting
