### ISSUE TITLE
Add themes to app

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#487]
- [x] Add backend calls to save the theme to the selected loop
- [x] Retrieve the loop theme from the /v2/chain?add-theme call
- [ ] Show a list of theme choices to select from, in the app settings page
- [ ] The the values of theme to change the colors used in the app, see https://ionicframework.com/docs/theming/color-generator

**Comment by Zahra46031** [comment]
I will be working on this part. Thank you!

**Comment by lil5** [comment]
@Zahra46031 Do you want to continue with the last 2 points?

**Comment by Zahra46031** [comment]
Yes, will be done by Monday
