### ISSUE TITLE
Design the email layout to make them look nicer

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#489]
Create a default html email template that is used for all email sent from `/server`

![Screenshot 2023-06-19 at 15 44 07](https://github.com/the-clothing-loop/website/assets/17646836/2b9d5fe9-0e42-4068-a22e-8cfeeccb1d61)

Use the above image as a guide, not rule

Use https://mailbakery.com/template-store/product/classy-free-html-email-template/ or your favourite start template as a start

- [x] Create html email template
- [x] Add layout to all mail functions (golang)
- [ ] Add LinkedIn?

**Comment by lil5** [comment]
@paloeka What do you think?

![Image](https://github.com/the-clothing-loop/website/assets/17646836/8e88093c-d098-4823-86a4-c17ce3173d97)

**Comment by paloeka** [comment]
Looks really good! Makes it look more professional.

Small changes:
Maybe we could add the Linkedin link in it as well.  
I think the mail, instagram, linkedin (in this order), looks even better if it is horizontal instead of vertical. But if that does not work on phone, we could leave it vertical

**Comment by lil5** [comment]
> looks even better if it is horizontal instead of vertical. But if that does not work on phone, we could leave it vertical

Sadly that won't look very nice on mobile

**Comment by lil5** [comment]
Social media buttons, facebook and instagram are added in the style of the website

![Image](https://github.com/the-clothing-loop/website/assets/17646836/d9356e54-114a-4db8-9de2-64a90cf10acf)
