### ISSUE TITLE
Move to using docker containers and plausible self hosted analytics

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#492]
- [ ] Move from using the linux vm as is to using docker containers for deployment.
- [ ] With that comes the ability to self host Plausible Analytics.

The deployment methods I've looked into that might be interesting to use are;
1. Dokku [link](https://dokku.com/docs/getting-started/installation/)
2. Coolify [link](https://coolify.io/)
3. Ssh + Docker engine
4. CapRover [link](https://caprover.com/)

Deployment strategies are open for changes and improvements!

**Comment by tobifaf** [comment]
@lil, this might be something I can assist in. I've mostly set this up in larger environments, but we might be able to think of something suitable?

**Comment by lil5** [comment]
The vps provider doesn't support docker on Debian without disabling AppArmour. Unless we move to a new Ubuntu based vps this issue can't happen. 

Docker will also add more moving parts to the server that might impact stability down the line. 

There is something to be said for keeping it simple with systemd services, without requiring networking knowledge to understand connections between docker containers. 

Were I to setup the vps today I would start with docker, but as it is now, it works, it's simple enough, it auto updates just fine, and I can reliably pass on the maintenance costs to another who only requires Linux knowledge. 

On top of that the app has my top first priority I can't put the stability of the server on the line.

**Comment by tobifaf** [comment]
all seem valid arguments. Might be a good idea to put an "on hold" label on this issue then

**Comment by lil5** [comment]
Goat Counter full fills our needs.
