### ISSUE TITLE
Delete account pop-up message

### ISSUE THREAD

**Issue by paloeka** [the-clothing-loop/website#495]
Old: "Are you sure you want to permanently delete your account?" User can click on Delete and Cancel

New:

"Are you sure you want to permanently delete your account?
As you are the only host of <Loop Name>, the Loop will also be deleted?"

Then first have to click on a button with Delete Loop and then on a Button with Delete Account

**Comment by lil5** [comment]
This requires the chains call to return the amount of hosts.
