### ISSUE TITLE
Change LinkedIn link

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#496]
The new linkedin link is https://www.linkedin.com/company/the-clothing-loop/

Please change this in the app and website

**Comment by MartinL-no** [comment]
Hey Lucian,

I seen this issue needed fixed so I made a pull request for it [here](https://github.com/the-clothing-loop/website/pull/497).

I'm interested in helping out on the project if there are any other issues you would like help with 😊

Thanks,
Martin
