### ISSUE TITLE
Add push notifications to native app

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#500]
Add push notifications must be able to be received even if the app is not open.

Actions for a notification:
- [x] A new bulky item has been created
- [x] The bag you are holding has been in your possession for too long
      (if the bag is longer than a week on the same address)

**Comment by lil5** [comment]
@paloeka Any actions I'm missing?

**Comment by paloeka** [comment]
No, I think this is it for now for the pushnotifications
