### ISSUE TITLE
Add a licenses page in app

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#519]
Using https://www.npmjs.com/package/nlf generate a page with the licenses used in the app.

- [ ] Create a list item below `Privacybeleid` (in Settings page) with the label `Open Source`
- [ ] Create an npm run script that runs a `generate-open-source-page.js` (see sitemap generation in frontend as example)
- [ ] The output of **nlf** (use a reach of 1) needs to be wrapped in a `<p>` tag and use a similar page design as the PrivacyPolicy page.

**Comment by tobifaf** [comment]
Hi @lil5, what exactly do you want to show in this page? Something like:

Module url (Licence) ? For example:
querystringify https://github.com/unshiftio/querystringify (MIT)

**Comment by lil5** [comment]
If you can parse through this list and make it nice, it would be best to make the list as dense as possible. 

`name (license name) <a href="url">link</a>`

Or list per license 
`<h3>license</h3>
name (license name) <a href="url">link</a>
`

Wrap the individual license names in `ul > li`

**Comment by tobifaf** [comment]
@lil5 , I've created a PR with a proposal: #557.
