### ISSUE TITLE
Change text in ‘thank you for signing up’ page + Verify email to clarify, see drive: communication --> email --> User Journey

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#520]

**Comment by lil5** [comment]
@paloeka Am I missing anything for this issue?

![Screenshot 2023-06-29 at 12 15 59](https://github.com/the-clothing-loop/website/assets/17646836/eca36d5e-62bc-4975-b734-aed5b39dea3b)

**Comment by paloeka** [comment]
Maybe add to 'Our confirmation email is on its way', to verify your account.

It is then: 

'Our confirmation email is on its way to verify your account'. 

Besides that it looks really good
