### ISSUE TITLE
Create cli tool that gets a couple of user coordinates from their address (don't over use map box free api key usage)

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#533]

**Comment by tobifaf** [comment]
Hi @lil5, did you ever consider https://openrouteservice.org/ ?

This might be more scalable than relying on a free api key, since you can self-host this entire solution if you scale up.

**Comment by lil5** [comment]
Mapbox has a maximum of 100 000 api requests per month, which we don't completely use

If the cli can automatically stop at 10 000 api requests there should be enough margin for normal operations 

Concerning the Mapbox map generating feature (which is calculated per web load) we aren't anywhere near the 50 000 mark.
