### ISSUE TITLE
Add Play Store and App Store icon to footer

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#538]
Add a white bar just above the teal bar (containing: tos, privacy,...)

App Store on the left the Play Store one the right, centered. 

On mobile the browser should detect which one to show. See http://browserhacks.com/

Assets:

https://play.google.com/intl/en_us/badges/

https://developer.apple.com/app-store/marketing/guidelines/

**Comment by saakshiraut28** [comment]
Hey @lil5, I would like to work on this issue.

**Comment by lil5** [comment]
Go for it,

As the app isn't past testing it'll take some time before it can be used, but I'll be glad to have the code already in there, commented out.

**Comment by saakshiraut28** [comment]
Alright @lil5. I'll start working on it.

**Comment by saakshiraut28** [comment]
Hey @lil5, could you please tell me in little detail how to access those images?

**Comment by lil5** [comment]
See how most images are using the images.clothingloop.org url have a look at those and it'll become apparent. If you've used something like cloudinary, it's a bit like that

**Comment by lil5** [comment]
`https://images.clothingloop.org/150x/<file name>`

You can use `150x` for width or `x150` height resizing

**Comment by saakshiraut28** [comment]
Got it. Thanks @lil5.

**Comment by lil5** [comment]
Thanks! As soon as we have published the apps I'll let you know when it's on production 😉

**Comment by saakshiraut28** [comment]
Ok.. I'll start working on it...

**Comment by lil5** [comment]
Your misunderstanding, the image is already there

**Comment by saakshiraut28** [comment]
Ok, Got it. My bad...
