### ISSUE TITLE
App native app install prompt

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#556]
Android https://developer.chrome.com/blog/app-install-banners-native/

iOS https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners

![](https://docs-assets.developer.apple.com/published/20ab7d726b/rendered2x-1605721898.png)

**Comment by lil5** [comment]
@saakshiraut28  If you're interested another easy win, that references the app

That aren't done yet 🙈

**Comment by saakshiraut28** [comment]
Yeah, I would love to contribute.🚀

**Comment by saakshiraut28** [comment]
Yeah, I would love to contribute.🚀

**Comment by lil5** [comment]
Great! Its all yours.

Please comment them out before sending the PR

**Comment by saakshiraut28** [comment]
Hey @lil5, I ain't getting much time to work on this issue as I got my exams scheduled for this week. :(

**Comment by lil5** [comment]
@saakshiraut28 this issue doesn't have a huge time stress, you can continue on it in 2 weeks if you like.

**Comment by lil5** [comment]
related links: https://pracucci.com/chrome-related-applications.html https://tools.applemediaservices.com/app/6451443500?country=us

**Comment by lil5** [comment]
Added to the `app` PWA
