### ISSUE TITLE
Add more in app notifications

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#562]
- [x] Somebody holds a bag for longer than 7 days
- [x] A new bulky item is added **priority**
- [ ] #742
- [x] Somebody else set you to a bag

**Comment by lil5** [comment]
@tobifaf If your interested?

Start off with finishing off `A new bulky item is added`, create a PR for that, then we call look at the others in this list

**Comment by tobifaf** [comment]
sure thing!

**Comment by lil5** [comment]
Awesome! for code references/example find the flow for **Somebody holds a bag for longer than 7 days**

**Comment by tobifaf** [comment]
@lil5 What exactly do you mean with that flow? I could only find:
https://github.com/the-clothing-loop/website/blob/60fbd78fe2fea9f4119c82f172cd726b2581edb0/app/src/pages/BagsList.tsx#L341C23-L341C23

**Comment by lil5** [comment]
@tobifaf https://github.com/the-clothing-loop/website/blob/main/server/internal/controllers/cron.go see the hourly cron

**Comment by tobifaf** [comment]
as discussed and tested, the "A new bulky item is added priority" is already working

**Comment by lil5** [comment]
**Somebody else set you to a bag** is fixed here: https://github.com/the-clothing-loop/website/pull/584

**Comment by tobifaf** [comment]
@lil5 can you have a look at this proposal for making sure users are not getting alot of the same notifications? https://github.com/the-clothing-loop/website/commit/bef9e99c9dca33c06ce023c824182cb9713f9de8

**Comment by lil5** [comment]
@tobifaf good idea, there are no in memory hashmap packages (think redis but living in the go runtime), we could use for a more global approach?

**Comment by tobifaf** [comment]
@lil5, concurrent-map seems a nice and simple solution. Do you prefer to have this as sort of a more generic "key/value in-application" db?

**Comment by lil5** [comment]
@tobifaf Before coding could you please create a mermaid document explaining what/how you want it to work.

**Comment by tobifaf** [comment]
sure thing!

**Comment by tobifaf** [comment]
@lil5 can you have a look at #658 ? This is my proposal for the debounced notification system.
