### ISSUE TITLE
Add mail queue

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#578]
A queue needs to be created to resend failed emails

only some emails are important enough to resend: 

1. A participant joined a loop
2. More?

**Comment by lil5** [comment]
@paloeka any thoughts on this?

**Comment by paloeka** [comment]
The Queue for reminder emails are sent twice, 3 times in total. We discussed to have a 24 hour period between every try. If after 3 times the email is still not sent, we get an email to hello@clothingloop.org. 

The emails that are important enough to resend:

an_admin_approved_your_join_request.gohtml
an_admin_denied_your_join_request.gohtml
approve_reminder.gohtml
poke.gohtml
register_verification.gohtml
someone_is_interested_in_joining_your_loop.gohtml

**Comment by lil5** [comment]
This should now be live
