### ISSUE TITLE
Remove bag name logic

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#600]
Currently the bag is sometimes prefixed by the translated word for bag

Here is how it currently works: https://github.com/the-clothing-loop/website/blob/ece43145501884e76001fe4d7d6a0683e37312ac/server/docs/bag_name.md

- [x] **Remove that bag logic**
  - [x] From the app
  - [x] From the website
  - [x] From the server
- [x] **Remove the above mentioned documentation**
- [x] **Add a migration sql script to be run so that the bags Look like they are the same:**
      From `{ translated_text_bag} Name`, find the language used for that loop, and replace with `Bag Name`

---
Here are the rules for the migration script:

1. The bags that have a name shorter than 7 characters will get a `Bag ` (in a translated form) prepended.
2. To figure out which language to translate it to, the related Loop and Hosts of said Loop must be retrieved:
   1. As there can be multiple hosts in one loop (often one being more active than the other) pick the host that contains a selected language, and set it as such.
   2. If the no host has set a language, default to `nl`.

An Error correction script must be added to find: 
1. all Bags with a `nl` prefix
2. and where its Loop country is not `nl` or `be`

This is to be run post migration to fix the handful of non-dutch loops

**Comment by tobifaf** [comment]
as discussed, I'll have a look

**Comment by tobifaf** [comment]
@lil5 I have a proposal in #610 
I'm not sure how you should handle the actual deployment since this mainly affects the app.

Prepending Bag/Sac/Tas does not always make the bagNumber > 7 chars. So you might end up showing something like: "Bag Bag 1" to users of the current version of the app.

**Comment by lil5** [comment]
In terms of deployment, the app must first be updated, then a day after it's release the sql script is run 

App Stores like to auto update in the evening, but yes I agree that this is a hard problem
