### ISSUE TITLE
Add host email notification participant left loop

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#602]
Add an email notification that a participant has left their Loop

Template:
```
Hi <Name (host)>,

<Name Participant> is no longer part of your <Loop Name> loop. They removed themselves from your Loop.
You will no longer find their information in your admin page on [www.clothingloop.org](http://www.clothingloop.org/)

If you have saved <Name Participant>’s information somewhere else, please delete their information.
```

**Comment by lil5** [comment]
@paloeka What to you think of to staggering these per week to give the host an overview each week of;
1. who has left, 
2. is waiting for approval, 
3. and has fully joined in the loop

**Comment by paloeka** [comment]
I think we need to send an instead message like the "somebody is interested in joining your loop" as somebody leaves. We could think about that in the future hosts could adjust prefrences that they get an overview of each week. I think an overview is a really nice idea, but that is not the feature of this issue.
