### ISSUE TITLE
Terms of Host acceptance

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#611]
To keep our legal team happy a separate Terms of Hosts will be published along with a number of other required elements;

- [x] Add a Terms of Hosts page, with a link to it in the footer
- [x] Add Terms of Hosts content
- [x] Add a required checkbox when creating a new Loop to accept the Terms of Hosts.
- [x] Create a non-escapable popup for all hosts that login.
- [x] ~~Create an sql script that forcefully logs-out all hosts.~~
- [x] Create an sql script to draft all loops from hosts that haven't accepted the terms of hosts, and a script to list the loops where only some co-hosts have without write action. (These are to be run 40 days after **non-escapable popup** is released)
- [x] Create a column in the users table `accepted_toh`

- [x] Run sql scripts
- [ ] Email (i.) zero host approved @paloeka 
- [ ] Email (ii.) 1 host 0 participants deleted chain @lil5 
- [ ] Email (iii.) some host approved toh @paloeka

**Comment by lil5** [comment]
@paloeka the Terms of Hosts only need to be accepted once right?

**Comment by paloeka** [comment]
1. No, only the Terms of Host need to be accepted once. By every host. If a host does not accept the Terms of Host, they can nolonger be host
2. No, but if it is easier if a new user automatically accept the Terms of Host by creation. We can implement it. If it is easier only to do it for hosts and new hosts, than that is fine as well.

**Comment by lil5** [comment]
I'll need the final version, If you could send it to me via slack I can incorporate it.

As it would only be a forced requirement on hosts (not participants) I'm implementing it as a separate checkbox.

I've only just started on it ;)

**Comment by lil5** [comment]
@paloeka 

1. The popup is ready, I just need some text for it. (see slack)
2. Should the popup also include a button to set yourself as participant and deny the Terms of Hosts?

**Comment by lil5** [comment]
Related: #670
