### ISSUE TITLE
App: Option to show bags as only tiles or cards

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#621]
In the App, In the list of bags page, add a button to change from current design (cards or if >18 list) to only list or only cards.

This is to be saved in localstorage, no api calls are necessary.

**Comment by lil5** [comment]
@paloeka is this a button/option that changes it for just that person or for the entire loop?

**Comment by paloeka** [comment]
My preference would go for that it just for that person. 

As every person should have the ability to get the "best" overview, and make the app work for them, I think it is better done on an individual level. It would matter less what a host decide for the rest of the Loop. We are the first starting point, than the host and finally a participant. I think it is most logical to go here for the individual preference of a participant.
