### ISSUE TITLE
Add reason for denying Loop access "no longer active"

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#625]
In the list of reasons to deny someone to a Loop should be the option "no longer active"

If clicked this will set the loop to draft, and a popup should be displayed on the draft toggle to indicate that it is automatically set to draft.

**Comment by lil5** [comment]
@paloeka What text would you like to have in that popup, shorter the better

**Comment by paloeka** [comment]
Let me know when it's done. Than we can change it in the https://docs.google.com/spreadsheets/d/1tSJuYb0lfCR7Cg1uD-XIDyT7HJSdVndh9DOw1yPChDs/edit

**Comment by lil5** [comment]
The translations are still to be added, but the new text should be arriving in Crowdin shortly.

Functionally this issue is done
