### ISSUE TITLE
Add new default rules to app

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#626]

**Comment by lil5** [comment]
@paloeka Is there a link you could add here to the latest App default rules?

**Comment by paloeka** [comment]
What do you mean? 

Do you mean this spreadsheet: https://docs.google.com/spreadsheets/d/1SAHeILvDPOj5nvshqrDyRkuQe_yL9My5TXp_Rv7LBDI/edit?gid=0#gid=0

**Comment by lil5** [comment]
spreadsheet might be to old
