### ISSUE TITLE
Move the bulky items to sub page of bags

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#684]
This will allow for enough space in the navbar for the in app chat to become available. #682

A Y ↔️ scrolling section can be added to the bags page to sow some of the bulky items with a button to go to the bulky items page.

**Comment by lil5** [comment]
@paloeka  This will not be possible when chat is merged, The way bulky items will be setup in the chat groups, they will be treated like normal chat messages with pictures. If we what it to be setup diffently lets talk about this next meeting.

**Comment by paloeka** [comment]
No, as we are now having the chat. This item is no longer relevant. This was an idea before we had the idea to merge the bulky items with the chat. And had a chat and bulky items at the bags, to create enough space in the bottom of the app

**Comment by paloeka** [comment]
Shall we make a Kanban column also for deleted issues, or is the deleting issues enough?

**Comment by lil5** [comment]
I've moved it to done, 30 days after it gets archived (removed from the board entirely)
