### ISSUE TITLE
Address flag (mini host)

### ISSUE THREAD

**Issue by lil5** [the-clothing-loop/website#730]
Some, more active, participants can be appointed as bag wardens along the Loop.

These wardens will have a flag icon in the address list(app)

Wardens, for now don't have extra authentication powers in the app or website, the idea is to have them check the bag, or other maintenance roles.

- [x] Hosts can assign a flag in the app from the `address item` page
- [x] Everyone can see the flag in the app from the `address list` page, located where the shield would go for hosts
- [x] A Host cannot be a Warden
- [x] title: Quality checkpoint
- [x] body: Responsible for extra quality control 
- [x] @paloeka Translations for warden title, body

**Comment by paloeka** [comment]
Translation to Dutch:

Title: Kwaliteitscheckpunt
Body: Deze deelnemer is verantwoordelijk voor een extra kwaliteitscontrole van de tas

Translation to German:
Title: Qualitätskontrollpunkt
Body: Diese(r) Teilnehmer*in ist für die zusätzliche Qualitätskontrolle der Tasche verantwortlich

**Comment by lil5** [comment]
@paloeka https://crowdin.com/editor/the-clothing-loop/71?view=multilingual&languages=nl,de&filter=basic&value=3#q=warden you can view crowdin as a spreadsheet to see many languages at once.

I have added these in crowdin
